# Generated by Django 3.0.5 on 2021-06-05 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_type',
            fields=[
                ('cab_type', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Cab Model')),
                ('cab_price', models.IntegerField(verbose_name='Price per day')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place', models.CharField(help_text='Add the name of the place', max_length=100, primary_key=True, serialize=False, verbose_name='Name of the Place')),
                ('type', models.TextField(choices=[('beach', 'BEACH'), ('hill', 'HILL STATION'), ('heritage', 'HERITAGE SITE')], max_length=10, verbose_name='Location Type')),
                ('description', models.TextField(help_text='Add 50 words escription about the place', max_length=500, verbose_name='Description of the Place')),
                ('location', models.CharField(max_length=50)),
                ('url', models.URLField(help_text='Add url of the image to be displayed', max_length=100, verbose_name='Image Url')),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('room_type', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Room Type')),
                ('description', models.TextField(help_text='Enter Description about the Room', max_length=500, verbose_name='Room Description')),
                ('child_price', models.IntegerField(verbose_name='price per child')),
                ('adult_price', models.IntegerField(verbose_name='Price per adult')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_children', models.IntegerField(verbose_name='No of Children')),
                ('no_of_Adults', models.IntegerField(verbose_name='No of Adults')),
                ('start_date', models.DateField(verbose_name='Check in Date')),
                ('end_date', models.DateField(verbose_name='Check out Date')),
                ('breakfast_included', models.BooleanField(help_text='check if you want breakfast', verbose_name='Breakfast included')),
                ('Total_price', models.IntegerField(verbose_name='Price of the total package')),
                ('cab_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cab_type', verbose_name='Select Cab Type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Place', verbose_name='Select Places')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Room_type', verbose_name=' Select Room Type')),
            ],
            options={
                'unique_together': {('place', 'room_type', 'start_date', 'end_date')},
            },
        ),
    ]
